version: "{build}"
branches:
  only:
    - master

cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
  - '%USERPROFILE%\.nuget\packages'

environment:
  repo_token: # Encrypted coveralls repository token
    secure: cLqzCAz4DJr0yy9SudBhqMP18FGcZJb9Lzojw8xeog4T+mZ2m9CNwmRQfaxYmuc5

os: Visual Studio 2022

platform: Any CPU

configuration:
  - Debug

build_script:
  - ps: ./build.ps1

artifacts:
  - path: "./tests/**/coverage.xml"
  - path: "./src/**/Rustic.*.nupkg"

deploy:
  - provider: NuGet # Nuget.org
    api_key:
      - secure: wB/TicV9Qsuqfs1X3excsY/wt/pBfqQDb/9kKFWQcCHTL0rQZNHaVqDiEWQ39U6L
    artifact: /.*(\.|\.s)nupkg/
    on:
      - branch: /release-/
  - provider: NuGet # Github packages
    server: https://nuget.pkg.github.com/ProphetLamb/index.json
    artifact: /.*\.nupkg/
    username: ProphetLamb
    api_key:
      - secure: C8xC+nv4MSirvCA8kUoan4sz2B8aFaytWW2m4lrLqXhAnSkOmo6fN90QHiGJoSGI
    on:
      - branch: /release-/
