version: "{build}"
branches:
  only:
    - master

cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
  - '%USERPROFILE%\.nuget\packages'
  #- C:\ProgramData\chocolatey\bin -> appveyor.yml
  #- C:\ProgramData\chocolatey\lib -> appveyor.yml

os: Visual Studio 2022

platform: Any CPU

configuration:
  - Debug

build_script:
  - ps: build.ps1

artifacts:
  - path: "./src/**/*.nupkg"
