version: "0.1.{build}"

cache:
  - '%USERPROFILE%\.nuget\packages'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

os: Visual Studio 2022

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

platform: Any CPU

configuration:
  - Debug

before_build:
  - choco install opencover.portable
  - choco install codecov
  - dotnet restore "src/"

build_script:
  - dotnet build "src/" --version-suffix %LABEL%

test_script:
  - dotnet test "src/" --no-build --no-restore --test-adapter-path:. --logger:"Appveyor;LogFilePath=./coverage.opencover.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - codecov -f "coverage.opencover.xml"

artifacts:
  - path: "coverage.opencover.xml"
