version: "0.5.{build}"

cache:
  - '%LocalAppData%\NuGet\Cache -> **\Rustic*.csproj'
  - '%LocalAppData%\NuGet\v3-cache  -> **\Rustic*.csproj'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: cLqzCAz4DJr0yy9SudBhqMP18FGcZJb9Lzojw8xeog4T+mZ2m9CNwmRQfaxYmuc5

os: Visual Studio 2022

install:
  # SDK version fix
  - cinst dotnet-sdk --version 6.0.101

artifacts:
  - path: 'src\**\Rustic.*.nupkg'
  - path: 'tests\**\coverage*.xml'

configuration:
  - Debug

dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - ps: $Env:DOTNET_CLI_TELEMETRY_OPTOUT=1
  - ps: $Env:DOTNET_NOLOGO=1
  - ps: dotnet restore -verbosity:q

build:
  parallel: true
  verbosity: minimal

test:
  assemblies:
    only:
      - 'tests\**\*.Tests.dll'

for:
  - branches: # Only pack and deploy nuget packages for releases
      only:
        - /release-/

    configuration:
      - Release

    deploy:
      - provider: NuGet # Nuget.org
        api_key:
          secure: wB/TicV9Qsuqfs1X3excsY/wt/pBfqQDb/9kKFWQcCHTL0rQZNHaVqDiEWQ39U6L
        artifact: /.*(\.|\.s)nupkg/
        on:
          branch: /release-/
      - provider: NuGet # Github packages
        server: https://nuget.pkg.github.com/ProphetLamb/index.json
        artifact: /.*\.nupkg/
        username: ProphetLamb
        api_key:
          secure: C8xC+nv4MSirvCA8kUoan4sz2B8aFaytWW2m4lrLqXhAnSkOmo6fN90QHiGJoSGI
        on:
          branch: /release-/
