os: Visual Studio 2022

init:
  - ps: $Env:DOTNET_CLI_TELEMETRY_OPTOUT=1
  - ps: $Env:DOTNET_NOLOGO=1

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: /zeidGSNfAh5zjjmnLcNsS98SbM+h/V+ST7ZZG/1n6LX8GLlMIvj6u4L7ivbtuBS

cache:
  - '%LocalAppData%\NuGet\Cache -> **\Rustic*.csproj'
  - '%LocalAppData%\NuGet\v3-cache  -> **\Rustic*.csproj'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%UserProfile%\.dotnet\tools -> appveyor.yml'

install:
  - choco install dotnet-sdk --version 6.0.101
  - ps: >-
      "& dotnet tool install --global coveralls.net"
      "& dotnet tool install -g XMLDoc2Markdown"

configuration:
  - Debug

version: "0.5.{build}"

dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - dotnet restore -verbosity:q

build:
  parallel: true
  verbosity: quiet

after_test:
  - ps: ./coveralls.net.ps1

test:
  assemblies:
    only:
      - 'tests\**\*.Tests.dll'

artifacts:
  - path: 'src\**\Rustic.*.nupkg'
  - path: 'tests\**\coverage*.xml'
  - path: '**\GeneratorTests.log'
  - path: 'doc\'

for:
  - branches: # Only pack and deploy nuget packages for releases
      only:
        - /release.*/

    configuration:
      - Release

    deploy:
      - provider: NuGet # Nuget.org
        api_key:
          secure: wB/TicV9Qsuqfs1X3excsY/wt/pBfqQDb/9kKFWQcCHTL0rQZNHaVqDiEWQ39U6L
        artifact: /.*(\.|\.s)nupkg/
        on:
          branch: /release.*/
      - provider: NuGet # Github packages
        server: https://nuget.pkg.github.com/ProphetLamb/index.json
        artifact: /.*\.nupkg/
        username: ProphetLamb
        api_key:
          secure: C8xC+nv4MSirvCA8kUoan4sz2B8aFaytWW2m4lrLqXhAnSkOmo6fN90QHiGJoSGI
        on:
          branch: /release.*/
