version: "{build}"

cache:
  - '%LocalAppData%\NuGet\Cache -> **\Rustic*.csproj'
  - '%LocalAppData%\NuGet\v3-cache  -> **\Rustic*.csproj'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  repo_token: # Encrypted coveralls repository token
    secure: cLqzCAz4DJr0yy9SudBhqMP18FGcZJb9Lzojw8xeog4T+mZ2m9CNwmRQfaxYmuc5

os: Visual Studio 2022

install:
  # SDK version fix
  - cinst dotnet-sdk --version 6.0.101

artifacts:
  - path: "./tests/**/coverage.xml"
  - path: "./src/**/Rustic.*.nupkg"

before_build:
  - ps: >-
      $Env:LABEL = if ($Env:APPVEYOR) { "${Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")}-${Env:APPVEYOR_REPO_BRANCH}" } else { "local" }

      $Env:DOTNET_CLI_TELEMETRY_OPTOUT=1

      $Env:DOTNET_NOLOGO=1

build_script:
  - ps: >-
      dotnet restore -verbosity:q

          echo "`n========================================================================================================================`n
          Build libs
          `n========================================================================================================================`n"

          Push-Location .\src

          foreach ($project in Get-ChildItem -Recurse Rustic*.csproj -File) {
              Push-Location $project.Directory

              echo "`n========================================================================================================================`nBuild $project`n"

              dotnet build -c:Debug --no-restore -verbosity:q --version-suffix $Env:LABEL

              Pop-Location
          }
          Pop-Location

test_script:
  - ps: >-
      $target_frameworks = [String[]] 'netstandard2.1', 'netcoreapp3.1', 'net5.0', 'net6.0'

      echo "`n========================================================================================================================`n
      Run and cover tests
      `n========================================================================================================================`n"

      Push-Location .\tests

      foreach ($project in Get-ChildItem -Recurse Rustic*Tests.csproj -File) {
          Push-Location $project.Directory

          echo "`n========================================================================================================================`nTest $project`n"

          foreach ($target in $target_frameworks) {
              dotnet test --framework:$target -verbosity:q /p:AltCover=true
          }

          Pop-Location
      }
      Pop-Location

for:
  - branches: # Only build and deploy nuget packages for releases
      only:
        - /release-/
    build_script:
      - ps: >-
          dotnet restore -verbosity:q

          echo "`n========================================================================================================================`n
          Build and pack libs
          `n========================================================================================================================`n"

          Push-Location .\src

          foreach ($project in Get-ChildItem -Recurse Rustic*.csproj -File) {
              Push-Location $project.Directory

              echo "`n========================================================================================================================`nBuild $project`n"

              dotnet build -c:Release --no-restore -verbosity:q --version-suffix $Env:LABEL

              dotnet pack -c:Release --no-restore --no-build -verbosity:q --version-suffix $Env:LABEL

              Pop-Location
          }
          Pop-Location

    deploy:
      - provider: NuGet # Nuget.org
        api_key:
          secure: wB/TicV9Qsuqfs1X3excsY/wt/pBfqQDb/9kKFWQcCHTL0rQZNHaVqDiEWQ39U6L
        artifact: /.*(\.|\.s)nupkg/
        on:
          branch: /release-/
      - provider: NuGet # Github packages
        server: https://nuget.pkg.github.com/ProphetLamb/index.json
        artifact: /.*\.nupkg/
        username: ProphetLamb
        api_key:
          secure: C8xC+nv4MSirvCA8kUoan4sz2B8aFaytWW2m4lrLqXhAnSkOmo6fN90QHiGJoSGI
        on:
          branch: /release-/
